/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastroclienteswing;

import JavaApplicaitionDAO.ClienteMapDAO;
import JavaApplicaitionDAO.IClienteDAO;
import JavaApplicationCliente.Clientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author natan
 */
public class TelaPrincipal extends javax.swing.JFrame {
        private DefaultTableModel modelo = new DefaultTableModel();
    
        private IClienteDAO ClienteDAO = new ClienteMapDAO();
        /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        lblNome = new javax.swing.JLabel();
        BoxName = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        CPF = new javax.swing.JLabel();
        BoxCPF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BoxEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BoxNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BoxCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BoxTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BoxEstado = new javax.swing.JTextField();
        Alterar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuItemSair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome:");

        BoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNameActionPerformed(evt);
            }
        });

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        CPF.setText("CPF:");

        BoxCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxCPFActionPerformed(evt);
            }
        });

        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Endereço:");

        BoxEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxEnderecoActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero:");

        BoxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNumeroActionPerformed(evt);
            }
        });

        jLabel3.setText("Cidade:");

        jLabel4.setText("Telefone:");

        jLabel6.setText("Estado:");

        Alterar.setText("Atualizar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        MenuItemSair.setText("opções");
        MenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSairActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuItemSair.add(jMenuItem1);

        jMenuBar1.add(MenuItemSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(BoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Salvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Excluir)
                                        .addGap(18, 18, 18)
                                        .addComponent(Alterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Limpar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BoxEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(BoxName))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(CPF))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BoxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BoxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BoxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(410, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(BoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPF)
                    .addComponent(BoxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(BoxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(BoxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(BoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(Excluir)
                    .addComponent(Alterar)
                    .addComponent(Limpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSairActionPerformed

    }//GEN-LAST:event_MenuItemSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                   int result;
            
        result = JOptionPane.showConfirmDialog(this,"Deseja sair da aplicação.", "Sair", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNameActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
       String nome = BoxName.getText();
       String Cpf = BoxCPF.getText();
       String Endereco = BoxEndereco.getText();
       String Numero = BoxNumero.getText();
       String Cidade = BoxCidade.getText();
       String Estado = BoxEstado.getText();
       String Telefone = BoxTelefone.getText();
       
       if(!IsValida(nome, Cpf, Endereco, Numero, Cidade, Estado, Telefone)){
          JOptionPane.showMessageDialog(null, "Preencha todos os campos",
         "Resultado", JOptionPane.INFORMATION_MESSAGE);
          return;
      }
       
       Clientes cliente = new Clientes(nome, Cpf, Endereco, Numero, Cidade, Estado, Telefone);
       Boolean isCadastrado = this.ClienteDAO.cadastrar(cliente);
       if(isCadastrado){
           modelo.addRow(new Object[]{cliente.getNome(), cliente.getCpf(), cliente.getEndereco(), cliente.getNumero(), cliente.getCidade(), cliente.getEstado(), cliente.getTelefone()});
           limparcampos();
       }else{
       JOptionPane.showMessageDialog(null, "Cliente ja cadastrado.",
         "ATENÇÃO!", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_SalvarActionPerformed

    private void BoxCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxCPFActionPerformed

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
            int result = TabelaClientes.getSelectedRow();
            Long Cpf = (Long) TabelaClientes.getValueAt(result, 1);
            
            Clientes cliente = this.ClienteDAO.consultar(Cpf);
            BoxName.setText(cliente.getNome());
            BoxCPF.setText(cliente.getCpf().toString());
            BoxEndereco.setText(cliente.getEndereco());
            BoxNumero.setText(cliente.getNumero().toString());
            BoxCidade.setText(cliente.getCidade());
            BoxEstado.setText(cliente.getEstado());
            BoxTelefone.setText(cliente.getTelefone().toString());
            
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
         int linha = TabelaClientes.getSelectedRow();
            if(linha >= 0){
              int result = JOptionPane.showConfirmDialog(this,"Deseja excluir essa pessoa", "AVISO", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
                
              if(result == JOptionPane.YES_OPTION){
                    Long Cpf = (Long) TabelaClientes.getValueAt(linha, 1);
                    this.ClienteDAO.excluir(Cpf);
                    modelo.removeRow(linha);
                    
                    JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso.",
         "AVISO!", JOptionPane.INFORMATION_MESSAGE);
                    
                }
            }else{
                JOptionPane.showMessageDialog(null, "Nenhum cliente selecionado.",
         "AVISO!", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void BoxEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxEnderecoActionPerformed

    private void BoxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNumeroActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
       int linhaSelecionada = TabelaClientes.getSelectedRow();
        
       if(linhaSelecionada >= 0){
       String nome = BoxName.getText();
       String Cpf = BoxCPF.getText();
       String Endereco = BoxEndereco.getText();
       String Numero = BoxNumero.getText();
       String Cidade = BoxCidade.getText();
       String Estado = BoxEstado.getText();
       String Telefone = BoxTelefone.getText();
       
       if(!IsValida(nome, Cpf, Endereco, Numero, Cidade, Estado, Telefone)){
          JOptionPane.showMessageDialog(null, "Preencha todos os campos",
         "Resultado", JOptionPane.INFORMATION_MESSAGE);
          return;
      }
       
      
       Clientes clientenovo = new Clientes(nome, Cpf, Endereco, Numero, Cidade, Estado, Telefone);
       this.ClienteDAO.alterar(clientenovo);
       
       modelo.removeRow(linhaSelecionada);
       modelo.addRow(new Object[]{clientenovo.getNome(), clientenovo.getCpf(), clientenovo.getEndereco(), clientenovo.getNumero(), clientenovo.getCidade(), clientenovo.getEstado(), clientenovo.getTelefone()});
       
       
       JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso.",
         "Resultado", JOptionPane.INFORMATION_MESSAGE);
          limparcampos();
       }else{
           JOptionPane.showMessageDialog(null, "Nenhum cliente selecionado",
         "Resultado", JOptionPane.INFORMATION_MESSAGE);
         
       }
       
    }//GEN-LAST:event_AlterarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
       limparcampos();
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JTextField BoxCPF;
    private javax.swing.JTextField BoxCidade;
    private javax.swing.JTextField BoxEndereco;
    private javax.swing.JTextField BoxEstado;
    private javax.swing.JTextField BoxName;
    private javax.swing.JTextField BoxNumero;
    private javax.swing.JTextField BoxTelefone;
    private javax.swing.JLabel CPF;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Limpar;
    private javax.swing.JMenu MenuItemSair;
    private javax.swing.JButton Salvar;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables

    private boolean IsValida(String ...campos) {
        for(String campo : campos){
           if(campos == null || "".equals(campo)){
               return false;              
           }
        }  
        return true;
    }

    private void initCustomComponents() {
        modelo.addColumn("Nome");
        modelo.addColumn("Cpf");
        modelo.addColumn("Endereco");
        modelo.addColumn("Numero");
        modelo.addColumn("Cidade");
        modelo.addColumn("Estado");
        modelo.addColumn("Telefone");
        
        
        
        TabelaClientes.setModel(modelo);

    }

    private void limparcampos() {
    BoxName.setText("");
    BoxCPF.setText("");
    BoxEndereco.setText("");
    BoxNumero.setText("");
    BoxCidade.setText("");
    BoxEstado.setText("");
    BoxTelefone.setText("");
    }
 
    public String toString(String Cpf) {
        return Cpf;
    }
}
